### PR TITLE
Detect brackets in filename

### LINKED ISSUE #102: Paths with a `[` and/or `]` in them are ignored
**What version of this package are you using?**
1.2.3

**What operating system, Node.js, and npm version?**
Mac OS 10.14.6

**What happened?**
I'm writing a NextJS app, and their pages directory structure uses brackets to define pretty URLs (e.g - `/[user_name]/messages` instead of `/messages?user_name=`)

This plugin seems to ignore files with brackets in the path, however. I get a "/my/path/[with]/brackets.js ignored." error in the JavaScript Standard Style output console when I save.

**What did you expect to happen?**
I expected the file to not be ignored.

**Are you willing to submit a pull request to fix this bug?**
Yes, if I knew where to start.

### PR DESCRIPTION
**Pull request by yuan9090**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix
[X] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Can Detect brackets in filename.

**Which issue (if any) does this pull request address?**
fix #102 [vscode-eslint#977](https://github.com/microsoft/vscode-eslint/issues/977)

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Review by theoludwig — APPROVED** [review]
Indeed, it solves the issue, I tested it manually on my computer and resolved the conflicts.
We can now have linting in files like `[test].js`.
Well done! @yuan9090

Since it's a bug fix and not a big change, I guess we can directy merge to master, if it was a feature request or something bigger, I would rather to have 2 approvals.

**Comment by edgarjs** [comment]
Thank you @yuan9090 !

@Divlo how is the release process for the extension? Should it get automatically updated or do I need to re-install it? I'm still new to vscode.

**Comment by feross** [comment]
@edgarjs We plan to release a new version as soon as the code on `master` has been tested by a few users since we've had a lot of code changes since the last release.

If you want to help out, can you test the code on `master` and report if it works for you? Post here: https://github.com/standard/vscode-standardjs/issues/135

**Comment by edgarjs** [comment]
@feross Thank you. It works! 

Screen Shot 2020-11-17 at 17 47 12

**Comment by lucas-santoni** [comment]
I originally noticed the same issue in version 1.4.0.

I tried `master` after this patch was merged and I observed the following message:

```json
{
	"resource": "/Users/geo/Documents/code/dessert-frontend/pages/module/[id].tsx",
	"owner": "standard",
	"severity": 8,
	"message": "Parsing error: \"parserOptions.project\" has been set for @typescript-eslint/parser.\nThe file does not match your project config: pages/module/%5Bid%5D.tsx.\nThe file must be included in at least one of the projects provided.",
	"source": "ts-standard",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
```

I'm working with a Next.js project. I'm using `ts-standard@9.0.0` The file I'm working with is named `[id].tsx`.

Running `ts-standard` outside VSCode works as expected.

**Comment by theoludwig** [comment]
@Geospace Thanks for your report, we'll try to fix this!
Where does this message appear ?
Could you copy/paste your `settings.json` (I mean `standard` extension related settings) there ?

**Comment by lucas-santoni** [comment]
This message appears in VSCode's "PROBLEMS" section. See here:

image

It only appears for files such as `[id].tsx` or `[slug].tsx`. Here are my `vscode-standardjs` extension settings:

```json
  "standard.engine": "ts-standard",
  "standard.autoFixOnSave": true,
  "standard.usePackageJson": true,
```

Just in case, my complete `settings.json` file is [available here](https://raw.githubusercontent.com/Geospace/dotfiles/master/vscode/settings.json).

Here is `package.json`:

```json
{
  "name": "front",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "ts-standard --fix"
  },
  "dependencies": {
    "@apollo/client": "^3.2.7",
    "github-markdown-css": "^4.0.0",
    "graphql": "^15.4.0",
    "lodash": "^4.17.20",
    "mobile-detect": "^1.4.4",
    "next": "^10.0.2",
    "normalize.css": "^8.0.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-grid-system": "^7.1.1",
    "react-icons": "^3.10.0",
    "react-infinite-scroll-component": "^5.1.0",
    "react-markdown": "^5.0.3",
    "react-select": "^3.1.0",
    "react-toastify": "^6.1.0"
  },
  "devDependencies": {
    "@types/lodash": "^4.14.165",
    "@types/node": "^14.14.9",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-select": "^3.0.26",
    "@types/webpack": "^4.41.25",
    "gray-matter": "^4.0.2",
    "next-mdx-remote": "^1.0.0",
    "ts-standard": "^9.0.0",
    "typescript": "4.0.5"
  },
  "ts-standard": {
    "ignore": [
      "next-env.d.ts"
    ]
  }
}
```

And here is `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": false,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "exclude": ["node_modules"],
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"]
}
```

Let me know if I can do anything else to help you debug this! I'll try to dig a bit more myself over the weekend or at least create a minimal repository that reproduces the issue.

**Comment by theoludwig** [comment]
Indeed, I find out how to reproduce. I had a hard time fixing the issue but hopefully it is now fine.
Could you tell me if #139 fix the issue ? @Geospace (maybe answer if it is working or not in the #139 PR not on this one)

**Pull request merged**
