### PR TITLE
Add support for ts-standard

### PR DESCRIPTION
**Pull request by LinusU**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Added support for ts-standard

**Which issue (if any) does this pull request address?**

#99 

**Is there anything you'd like reviewers to focus on?**

Currently I'm getting the following error when linting any file:

```text
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: file:/Users/linus/coding/my-project/my-file.ts.
The file must be included in at least one of the projects provided.standard
```

I'm thinking that it might have to do with the path being passed as the full path instead of just `my-file.ts`? 🤔 

Would love some help here! ping @chenxsan

### CODE REVIEW

**Comment by chenxsan** [comment]
@LinusU Might be related to https://github.com/typescript-eslint/typescript-eslint/issues/885? Since we use [`lintText`](https://github.com/standard/vscode-standardjs/blob/master/server/src/server.ts#L799).

**Comment by cyrilchapon** [comment]
Hey my friend.

Pretty new to vscode extensions; but can I help with something ?
I deadly need this.

**Comment by LinusU** [comment]
Hey @cyrilchapon, I really want this in but I haven't had any more time to look into it. The `vscode-eslint` plugin, from which this codebase was once forked, has support for ESLint TypeScript, so we should be able to get it working by looking how they are doing it.

They have also said that they would accept a PR for automatically detecting `standard` and friends which I personally think would be amazing, since it would ease our maintenance burden: https://github.com/microsoft/vscode-eslint/issues/498

-----

I'm currently using this ugly workaround, which you might like in the meantime:

Create a file named `.eslintrc.js` in the root of your project, with the following content:

```js
// FIXME:
// This file is not being used by the testing infrastructure, it's only here to tell VS Code which settings to use.
// https://github.com/microsoft/vscode-eslint/issues/498

module.exports = {
  parserOptions: {
    project: './tsconfig.json',
    tsconfigRootDir: __dirname
  },
  extends: [
    'standard-with-typescript',
    'standard-jsx'
  ]
}
```

You do not need to add any other dependency or anything, this will just tell the ESLint VSCode plugin to use `ts-standard`.

**Comment by cyrilchapon** [comment]
Wow.

> They have also said that they would accept a PR for automatically detecting standard and friends which I personally think would be amazing, since it would ease our maintenance burden: microsoft#498

This part would have so much value. I'm in the exact same case; having to switch between standard-vscode and eslint-vscode regarding the project is a real pain in the a\*\*, and having a single extension for both (+ ts-standard and afficionados) would make some people life easier.

IMHO even standard core-team could contribute on this; because I think I'm not the only on earth to have had a thought once like

> Hum... what if I just kept vscode-eslint, and trade standard for eslint-config-standard in every project I maintain... ?

I love `standard` syntactic sugar to much to do such a thing; but I confess I thought of doing this 2 or 3 times...

**Comment by toddbluhm** [comment]
@LinusU nice work! I was looking into adding `ts-standard` to this as well. This will be great when it is merged.

Edit:
The error your getting is usually related to the file your linting not being included in the typescript `tsconfig.json` file. 

Often when I set up a project using`tsconfig.json` I specify only the build files I want output to say `/lib`. But for example, test files that I want linted, but not built I will add in a `tsconfig.eslint.json` that extends `tsconfig.json` that only applies to `eslint`. I believe that might be what your error is complaining about. 

See https://github.com/typescript-eslint/typescript-eslint/issues/967 for more detail.

Also see `typescript-eslint` config options here: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/parser/README.md#parseroptionsproject

**Comment by toddbluhm** [comment]
I was able to get `ts-standard` to work with this PR! 🎉 

No significant changes to this PR were needed, most of the work had to do with fixing up `ts-standard` to be compatible with how this extension calls the library and properly passing in the working directory. I will hopefully have `ts-standard` updated to be compatible soon.

**Comment by LinusU** [comment]
Awesome! 👏 ❤️

**Comment by toddbluhm** [comment]
@LinusU I just published `ts-standard@8.0.0` give that a try with this PR. I had it all running successfully locally. Let me know if you run into any issues with this.

Using the extension, `ts-standard` should now be able to auto-detect the `tsconfig.json` or `tsconfig.eslint.json` file in the workspace directory. You can also use `package.json` to specify `project` or other settings to `ts-standard`. 

I believe you can also use this extension's `options` settings to provide the same settings that would normally go in a `package.json`. Admittedly I did not thoroughly test this out as it really does not make much sense to specify such settings editor/workspace wide when you can just put them in `package.json`. With that said, the editor `options` will override any `package.json` options.

**Comment by nebiros** [comment]
Just test it, works as expected, 🎉

**Comment by LinusU** [comment]
That's great news! 🚀

**Review by toddbluhm — APPROVED** [review]
Looks good to me. I also tested it locally and it works well.

**Comment by toddbluhm** [comment]
@mightyiam mind giving this a quick review? I prefer having at least two approvers before merging anything in.

**Comment by mightyiam** [comment]
Forgive me, @toddbluhm. I don't know this codebase and would rather not study it. I have enough open source to do already. Perhaps someone else or just one reviewer?

**Comment by amjerm** [comment]
Hi. Looking forward to this. Any update on when this will be merged?

**Comment by Webbanditten** [comment]
Im also looking forward to this. Bump

**Comment by theoludwig** [comment]
Yep, looking forward for this too. 🙂

**Comment by theoludwig** [comment]
@feross Can you approve this pull-request ?
We really need that...

**Comment by toddbluhm** [comment]
I apologize for the delay on this. Since I reviewed it and approved it, I will merge it. However, I do not have the ability to actually release a new version of the plugin. Another maintainer with access will have to do that.

**Comment by feross** [comment]
Please see: https://github.com/standard/vscode-standardjs/issues/121 I need help getting the code on `master` to build successfully so I can publish a new version. PRs welcome!

**Pull request merged**
