### PR TITLE
Release/v1.5.0

### LINKED ISSUE #111: Add extension to Open VSX Registry
**What version of this package are you using?**
N/A

**What problem do you want to solve?**
StandardJS is only available on the Microsoft VSCode Marketplace. This prevents it from being used by open-source versions of VSCode (i.e. VSCodium, Theia).

**What do you think is the correct solution to this problem?**
Also publish the extension to [Open VSX](https://open-vsx.org), guide available [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

**Are you willing to submit a pull request to implement this change?**
N/A

### LINKED ISSUE #131: Looking for a maintainer!
We're looking for a new maintainer or two to help with this repo. This extension has 300k+ users on VSCode – your work will have a huge impact!

Good first issues:

- Update TypeScript to the latest version https://github.com/standard/vscode-standardjs/issues/130
- Test out this PR and confirm it works: https://github.com/standard/vscode-standardjs/pull/126
- Go through the open issues and send PRs for any that look easy to fix
- Go through the open issues and comment "This issue should be closed" for the issues that are invalid/already fixed/duplicate, etc.

### LINKED ISSUE #135: Seeking testers! Confirm that the version on `master` works so we can publish a new version
Thanks to @Divlo's efforts in https://github.com/standard/vscode-standardjs/pull/132, this extension has been massively updated for the latest version of TypeScript and it now passes the `ts-standard` linter.

Since the changes were quite large, before we put out a new release, **I'd like at least 5 VSCode users to run the code on `master` and report no problems.**

If you'd like to test it out and confirm it works for your use case, then please follow these steps:

1. Run `npm install`
2. Run `npm run package` to build a .vsix file
3. You can install it with `code --install-extension vscode-standardjs.vsix`

If everything works for you, post a comment here indicating it worked for you.

### LINKED ISSUE #156: ts-standard parser error: the file does not match your project config
**What version of this package are you using?**

1.4.0

**What operating system, Node.js, and npm version?**

Windows 10, Node: v12.8.1, npm: 6.14.5

**What happened?**

I currently have a yarn workspace monorepo setup. When running ts-standard I get the following error for any file I open in my react project

```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: ..\..\..\..\..\..\c%3A\Users\[redacted]\packages\web\src\App.tsx.
The file must be included in at least one of the projects provided.
```

ts-standard seems to work fine on its own via CLI.

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

If I an understand what is causing it I'd be happy to help fix it.

### PR DESCRIPTION
**Pull request by theoludwig**
**What is the purpose of this pull request? (put an "X" next to item)**

- [x] Documentation update
- [x] Bug fix
- [ ] New feature
- [x] Other, please explain: Usage of GitHub Actions instead of Travis CI + continuous-deployment

**Which issue (if any) does this pull request address?**

closes #111, #131, #135

Closing #131 since the VSCode extension is now actually maintained but of course we always welcome contributors.

**Description**

Time to release a new version, I think lot of people will benefit from this! :rocket: 

Basically this PR increase the version number `1.4.0` to `1.5.0`, update the changelog so it's no longer `pending`.
I also deleted `&& settings.engine !== 'standard'` of this line https://github.com/standard/vscode-standardjs/blob/0f92bb6687eed39734d459c8a65594c67fd3d8aa/server/src/server.ts#L892
As it is discussed in #135 

Also use GitHub Actions instead of Travis, as it is the case on `standard` repo since https://github.com/standard/standard/pull/1629.

And also add **continuous-deployment**, everytime we release a new version on GitHub it also releases on *VSCode Marketplace* and *open-vsx* automatically.

To do that, we need to set 2 new secrets on the GitHub repo :
- `OPEN_VSX_TOKEN` : see https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#2-create-the-namespace
- `VS_MARKETPLACE_TOKEN` : see https://code.visualstudio.com/api/working-with-extensions/publishing-extension

I package the extension again and test it massively again to ensure everything working as expected also there are 5+ people saying it is working for them.

Here are some screenshots :

### CODE REVIEW

**Comment by aldeed** [comment]
Hi, I'd love to have the `[]` filename fix. Is this release close to being ready? Thanks

**Comment by theoludwig** [comment]
Hey! @aldeed 
The release is ready, we need someone to approve this PR changes from the `standard/team` and someone to add the `OPEN_VSX_TOKEN` and `VS_MARKETPLACE_TOKEN` secrets in the GitHub repository to allow automated deployment.

While we're waiting, we would appreciate if you could tell us that everything is working as expected in this new release by following these steps to install the extension locally :
```sh
git clone https://github.com/standard/vscode-standardjs.git
cd vscode-standardjs
git checkout release/v1.5.0
npm install
npm run package
code --install-extension vscode-standardjs-1.5.0.vsix
# restart VSCode
```

Maybe you could post a screen, that everything is working for you or if it's not the case, feel free to open a new issue.
Thanks for your help! :smile:

**Review by feross — APPROVED** [review]
LGTM

**Comment by aldeed** [comment]
@Divlo I built and installed locally and confirmed the issue with brackets in filenames is fixed (standard checking and auto-fixing works in those files). Thanks for the fix.

**Comment by feross** [comment]
- Created an Open VSX account, generated token, asked to be verified for `standard` namespace: https://github.com/EclipseFdn/open-vsx.org/issues/383
- Added the OPEN_VSX_TOKEN and VS_MARKETPLACE_TOKEN tokens as @Divlo requested. I haven't tested if the publish process actually works. Will leave that to @Divlo

**Pull request merged**
